import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google"
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en"className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className={`${poppins.variable} min-h-full flex flex-col`}>
        <Navbar/>
        <main> {children}</main>
        <Footer/>
        </body>
    </html>
  );
}
